using System;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace BccCode.I18N.SourceGen;

[Generator]
public class I18NLanguageKeyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var fallbackLanguage = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.FallbackLanguage", out var lang);
                return string.IsNullOrWhiteSpace(lang) ? "no" : lang!;
            });

        // Filter for the fallback language JSON file among AdditionalFiles
        var additionalFiles = context.AdditionalTextsProvider
            .Combine(fallbackLanguage)
            .Where(x => x.Left.Path.EndsWith($"{x.Right}.json", StringComparison.OrdinalIgnoreCase))
            .Select((x, _) => x.Left);

        context.RegisterSourceOutput(additionalFiles, GenerateCode);
    }

    private void GenerateCode(SourceProductionContext context, AdditionalText t)
    {
        try
        {
            var content = t.GetText(context.CancellationToken)?.ToString();
            if (content == null)
                return;

            using var doc = JsonDocument.Parse(content);
            if (doc.RootElement.ValueKind != JsonValueKind.Object) return;

            const string className = "I18N";
            var body = GenerateCSharp(doc.RootElement, "", "    ");
            var source = $$"""
                           // <auto-generated/>
                           #pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
                           public static class {{className}}
                           {
                           {{body}}
                           }
                           """;

            context.AddSource($"{className}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
        catch (Exception)
        {
            // You may want to log or report a diagnostic here in production
        }
    }

    private static string GenerateCSharp(JsonElement element, string outerPath, string indent)
    {
        var sb = new StringBuilder();

        foreach (var prop in element.EnumerateObject())
        {
            var name = prop.Name;
            if (prop.Value.ValueKind == JsonValueKind.Object)
            {
                sb.AppendLine($"{indent}public static class {SanitizeName(name)}");
                sb.AppendLine($"{indent}{{");
                sb.Append(GenerateCSharp(prop.Value, string.IsNullOrEmpty(outerPath) ? name : $"{outerPath}.{name}", indent + "    "));
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                var value = prop.Value.GetRawText();
                var keyPath = string.IsNullOrEmpty(outerPath) ? name : $"{outerPath}.{name}";
                if(value != null)
                    sb.AppendLine($"{indent}/// {value.Replace("\n", "/// ").Replace("\r", "///")}");
                else
                    sb.AppendLine("//No details found");
                sb.AppendLine($"{indent}public const string {SanitizeName(name)} = \"{keyPath}\";");
            }
        }
        return sb.ToString();
    }

    private static string SanitizeName(string name)
    {
        // Very basic: replace invalid identifier characters with '_'
        var sb = new StringBuilder();
        if (!SyntaxFacts.IsIdentifierStartCharacter(name[0]))
            sb.Append('_');
        if (SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None)
            sb.Append("@");
        foreach (var c in name)
            sb.Append(SyntaxFacts.IsIdentifierPartCharacter(c) ? c : '_');

        return sb.ToString();
    }
}