using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace BccCode.I18N.SourceGen;

internal static class I18NLanguageKeyGenerator
{
    public static void AddSource(SourceProductionContext context, TranslationModelSet translations)
    {
        const string className = "LanguageKeys";
        var body = GenerateMembers(TranslationTreeBuilder.BuildTree(translations.FallbackFile.Entries), "    ");
        var sourceBody = $$"""
                         public static class {{className}}
                         {
                         {{body}}
                         }
                         """;
        var source = $$"""
                       // <auto-generated/>
                       #pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
                       {{TranslationGeneratorUtilities.WrapInNamespace(sourceBody, translations.GeneratedNamespace)}}
                       """;

        context.AddSource($"{className}.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateMembers(TranslationNode node, string indent)
    {
        var builder = new StringBuilder();

        foreach (var child in node.Children.Values)
        {
            if (child.Children.Count > 0)
            {
                builder.AppendLine($"{indent}public static class {TranslationGeneratorUtilities.SanitizeName(child.Name)}");
                builder.AppendLine($"{indent}{{");
                builder.Append(GenerateMembers(child, indent + "    "));
                builder.AppendLine($"{indent}}}");
            }
            else
            {
                builder.AppendLine($"{indent}/// {TranslationGeneratorUtilities.EscapeXmlDoc(child.Value ?? string.Empty)}");
                builder.AppendLine($"{indent}public const string {TranslationGeneratorUtilities.SanitizeName(child.Name)} = {TranslationGeneratorUtilities.ToCSharpStringLiteral(child.KeyPath ?? string.Empty)};");
            }
        }

        return builder.ToString();
    }
}