using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace BccCode.I18N.SourceGen;

internal static class I18NLanguageGenerator
{
    public static void AddSource(SourceProductionContext context, TranslationModelSet translations)
    {
        const string className = "Language";

        var translationsByKey = BuildTranslationsByKey(translations.Files);
        var root = TranslationTreeBuilder.BuildTree(translations.FallbackFile.Entries);

        var body = GenerateMembers(context, root, translationsByKey, translations.FallbackLanguage, "    ");
        var sourceBody = $$"""
                 public static class {{className}}
                 {
                 {{body}}
                 }
                 """;
        var source = $$"""
                       // <auto-generated/>
                       using System;
                       using System.Globalization;

                       #pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
                   {{TranslationGeneratorUtilities.WrapInNamespace(sourceBody, translations.GeneratedNamespace)}}
                   """;

        context.AddSource($"{className}.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static Dictionary<string, Dictionary<string, string>> BuildTranslationsByKey(EquatableArray<LanguageFileModel> files)
    {
        var translationsByKey = new Dictionary<string, Dictionary<string, string>>(StringComparer.Ordinal);
        foreach (var file in files)
        {
            foreach (var entry in file.Entries)
            {
                if (!translationsByKey.TryGetValue(entry.KeyPath, out var valuesByLanguage))
                {
                    valuesByLanguage = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                    translationsByKey.Add(entry.KeyPath, valuesByLanguage);
                }

                valuesByLanguage[file.Language] = entry.Value;
            }
        }

        return translationsByKey;
    }

    private static string GenerateMembers(
        SourceProductionContext context,
        TranslationNode node,
        Dictionary<string, Dictionary<string, string>> translationsByKey,
        string fallbackLanguage,
        string indent)
    {
        var builder = new StringBuilder();

        foreach (var child in node.Children.Values)
        {
            if (child.Children.Count > 0)
            {
                builder.AppendLine($"{indent}public static class {TranslationGeneratorUtilities.SanitizeName(child.Name)}");
                builder.AppendLine($"{indent}{{");
                builder.Append(GenerateMembers(context, child, translationsByKey, fallbackLanguage, indent + "    "));
                builder.AppendLine($"{indent}}}");
                continue;
            }

            if (child.KeyPath is null || child.Value is null || !translationsByKey.TryGetValue(child.KeyPath, out var translations))
            {
                continue;
            }

            builder.Append(GenerateLeaf(context, child.Name, child.KeyPath, child.Value, translations, fallbackLanguage, indent));
        }

        return builder.ToString();
    }

    private static string GenerateLeaf(
        SourceProductionContext context,
        string name,
        string keyPath,
        string fallbackValue,
        Dictionary<string, string> translations,
        string fallbackLanguage,
        string indent)
    {
        var builder = new StringBuilder();
        var isPlural = fallbackValue.Contains("|", StringComparison.Ordinal);
        var parameters = TranslationGeneratorUtilities.GetParameterNames(fallbackValue, isPlural);

        builder.AppendLine($"{indent}/// {TranslationGeneratorUtilities.EscapeXmlDoc(fallbackValue)}");
        builder.Append($"{indent}public static string {TranslationGeneratorUtilities.SanitizeName(name)}");

        if (parameters.Length == 0)
        {
            builder.AppendLine(" =>");
        }
        else if (isPlural)
        {
            builder.Append("(int ").Append(parameters[0]);
            foreach (var parameter in parameters.Skip(1))
            {
                builder.Append(", object ").Append(parameter);
            }

            builder.AppendLine(") =>");
        }
        else
        {
            builder.Append('(')
                .Append(string.Join(", ", parameters.Select(static parameter => "object " + parameter)))
                .AppendLine(") =>");
        }

        if (isPlural)
        {
            builder.AppendLine($"{indent}  ({parameters[0]}, CultureInfo.CurrentUICulture.TwoLetterISOLanguageName) switch");
            builder.AppendLine($"{indent}  {{");

            foreach (var translation in translations
                         .Where(pair => !string.Equals(pair.Key, fallbackLanguage, StringComparison.OrdinalIgnoreCase))
                         .OrderBy(static pair => pair.Key, StringComparer.Ordinal))
            {
                AppendPluralCases(context, builder, keyPath, translation.Key, translation.Value, parameters, indent + "    ");
            }

            AppendPluralCases(context, builder, keyPath, fallbackLanguage, fallbackValue, parameters, indent + "    ", isFallback: true);
            builder.AppendLine($"{indent}  }};");
        }
        else
        {
            builder.AppendLine($"{indent}  CultureInfo.CurrentUICulture.TwoLetterISOLanguageName switch");
            builder.AppendLine($"{indent}  {{");

            foreach (var translation in translations
                         .Where(pair => !string.Equals(pair.Key, fallbackLanguage, StringComparison.OrdinalIgnoreCase))
                         .OrderBy(static pair => pair.Key, StringComparer.Ordinal))
            {
                if (!TryCreateExpression(context, keyPath, translation.Key, translation.Value, parameters, out var expression))
                {
                    continue;
                }

                builder.AppendLine($"{indent}    \"{translation.Key}\" => {expression},");
            }

            TranslationGeneratorUtilities.TryCreateFormatExpression(fallbackValue, parameters, out var fallbackExpression);
            builder.AppendLine($"{indent}    _ => {fallbackExpression},");
            builder.AppendLine($"{indent}  }};");
        }

        builder.AppendLine();
        return builder.ToString();
    }

    private static void AppendPluralCases(
        SourceProductionContext context,
        StringBuilder builder,
        string keyPath,
        string language,
        string value,
        string[] parameters,
        string indent,
        bool isFallback = false)
    {
        var parts = TranslationGeneratorUtilities.SplitPluralParts(value);
        for (var index = 0; index < parts.Length; index++)
        {
            if (!TryCreateExpression(context, keyPath, language, parts[index], parameters, out var expression))
            {
                return;
            }

            var plurality = index == parts.Length - 1 ? "_" : index.ToString();
            var languagePattern = isFallback ? "_" : $"\"{language}\"";
            builder.AppendLine($"{indent}({plurality}, {languagePattern}) => {expression},");
        }
    }

    private static bool TryCreateExpression(
        SourceProductionContext context,
        string keyPath,
        string language,
        string value,
        string[] parameters,
        out string expression)
    {
        if (TranslationGeneratorUtilities.TryCreateFormatExpression(value, parameters, out expression))
        {
            return true;
        }

        var unsupportedPlaceholders = TranslationGeneratorUtilities.GetUnsupportedPlaceholders(value, parameters);
        context.ReportDiagnostic(Diagnostic.Create(
            TranslationGeneratorDiagnostics.PlaceholderMismatch,
            Location.None,
            $"Translation key '{keyPath}' in language '{language}' uses placeholders [{string.Join(", ", unsupportedPlaceholders)}] that are not present in the fallback language. The fallback translation will be used instead."));
        return false;
    }
}