using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace BccCode.I18N.SourceGen;

[Generator]
public class I18NLanguageGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.AdditionalTextsProvider
            .Where(x => x.Path.EndsWith(".json"))
            .Collect();
        
        context.RegisterSourceOutput(provider, GenerateCode);
    }

    private void GenerateCode(SourceProductionContext context, ImmutableArray<AdditionalText> files)
    {
        const string className = "Language";

        try
        {
            var baseFile = files.FirstOrDefault(x => x.Path.EndsWith("no.json"));

            var content = baseFile?.GetText()?.ToString();
            if (content == null)
                throw new Exception("Not found");

            using var doc = JsonDocument.Parse(content);
            if (doc.RootElement.ValueKind != JsonValueKind.Object) throw new Exception("Not an object");

            var keys = files
                .SelectMany(GetLanguageMap)
                .GroupBy(x => x.key)
                .ToDictionary(x => x.Key, x => x.ToDictionary(y => y.language, y => y.value));

            var body = GenerateCSharp(doc.RootElement, keys, null, "    ");
            var source = $$"""
                           // <auto-generated/>
                           using System.Globalization;
                           
                           #pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
                           public static class {{className}}
                           {
                           {{body}}
                           
                           }
                           """;
            context.AddSource($"{className}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
        catch (Exception e)
        {
            context.AddSource($"{className}.g.cs", SourceText.From($"{e.Message}\n{e.StackTrace}", Encoding.UTF8));
        }
    }

    private static (string language, string key, string value)[] GetLanguageMap(AdditionalText additionalFile)
    {

        var language = Path.GetFileNameWithoutExtension(additionalFile.Path);

        var content = additionalFile?.GetText()?.ToString();
        if (content == null)
            return [];

        using var doc = JsonDocument.Parse(content);
        if (doc.RootElement.ValueKind != JsonValueKind.Object) return [];

        return GetLanguageMap(doc.RootElement)
            .Select(x => (language, x.Item1, x.Item2))
            .ToArray();
    }

    private static IEnumerable<(string, string)> GetLanguageMap(JsonElement root, string? outerPath = null)
    {
        foreach (var prop in root.EnumerateObject())
        {
            var name = prop.Name;
            var key = outerPath == null ? name : outerPath + "." + name;
            if (prop.Value.ValueKind == JsonValueKind.String)
            {
                yield return (key, prop.Value.ToString());
            }
            else if (prop.Value.ValueKind == JsonValueKind.Object)
            {
                foreach (var valueTuple in GetLanguageMap(prop.Value, key))
                {
                    yield return valueTuple;
                }
            }

        }
    }


    private static string GenerateCSharp(
        JsonElement element,
        Dictionary<string, Dictionary<string, string>> keys,

    string? outerPath, string indent)
    {
        var sb = new StringBuilder();

        foreach (var prop in element.EnumerateObject())
        {
            var name = prop.Name;
            var key = outerPath == null ? name : outerPath + "." + name;
            if (prop.Value.ValueKind == JsonValueKind.Object)
            {
                sb.AppendLine($"{indent}public static class {SanitizeName(name)}");
                sb.AppendLine($"{indent}{{");
                sb.Append(GenerateCSharp(prop.Value, keys, key, indent + "    "));
                sb.AppendLine($"{indent}}}");
            }
            else if (prop.Value.ValueKind == JsonValueKind.String)
            {
                var value = prop.Value.ToString();

                sb.AppendLine($"{indent}/// {prop.Value.ToString().Replace("\n", "\\n")}");
                sb.Append($"{indent}public static string {SanitizeName(name)}");

                var isPlural = value.Contains("|");
                var matches = Regex.Matches(value, @"\{(\s*\w+\s*)\}");
                var parameters = matches.Cast<Match>().Select(x => x.Groups[1].Value.Trim()).Distinct().ToArray();
                if (isPlural && parameters.Length == 0)
                {
                    parameters = ["count"];
                }

                if (parameters.Length == 0)
                {
                    sb.AppendLine(" => ");
                }
                else if (isPlural)
                {
                    // first parameter is int
                    sb.Append("(int " + parameters[0]);
                    sb.Append(string.Join("", parameters.Skip(1).Select(x => ", object " + x)));
                    sb.AppendLine(") => ");
                }
                else
                {
                    sb.Append("(" + string.Join(", ", parameters.Select(x => "object " + x)));
                    sb.AppendLine(") => ");
                }

                var languages = keys[key];
                var defaultValue = languages["no"];
                if (isPlural)
                {
                    sb.AppendLine($$"""{{indent}}  ({{parameters[0]}}, CultureInfo.CurrentUICulture.TwoLetterISOLanguageName) switch {""");
                    foreach (var language in languages.Where(x => x.Key != "no"))
                    {
                        var parts = language.Value.Split('|');
                        for (int i = 0; i < parts.Length; i++)
                        {
                            var plurality = i == parts.Length - 1 ? "_" : i.ToString();
                            sb.AppendLine($$"""{{indent}}    ({{plurality}}, "{{language.Key}}") => $"{{parts[i].Trim().Replace("\n", "\\n")}}", """);
                        }
                    }

                    {
                        var parts = defaultValue.Split('|');
                        for (int i = 0; i < parts.Length; i++)
                        {
                            var plurality = i == parts.Length - 1 ? "_" : i.ToString();
                            sb.AppendLine($$"""{{indent}}    ({{plurality}}, _) => $"{{parts[i].Trim().Replace("\n", "\\n")}}", """);
                        }
                    }
                    sb.AppendLine($$"""{{indent}}  };""");
                }
                else
                {
                    sb.AppendLine($$"""{{indent}}  (CultureInfo.CurrentUICulture.TwoLetterISOLanguageName) switch {""");
                    foreach (var language in languages.Where(x => x.Key != "no"))
                    {
                        sb.AppendLine($$"""{{indent}}    "{{language.Key}}" => $"{{language.Value.Replace("\n", "\\n")}}", """);
                    }

                    sb.AppendLine($$"""{{indent}}    _ => $"{{defaultValue.Replace("\n", "\\n")}}", """);
                    sb.AppendLine($$"""{{indent}}  };""");
                }

                sb.AppendLine();

            }
        }
        return sb.ToString();
    }

    private static string SanitizeName(string name)
    {
        // Very basic: replace invalid identifier characters with '_'
        var sb = new StringBuilder();
        if (!SyntaxFacts.IsIdentifierStartCharacter(name[0]))
            sb.Append('_');
        if (SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None)
            sb.Append("@");
        foreach (var c in name)
            sb.Append(SyntaxFacts.IsIdentifierPartCharacter(c) ? c : '_');

        return sb.ToString();
    }
}