using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace BccCode.I18N.SourceGen;

internal static class I18NLanguageDictGenerator
{
    public static void AddSource(SourceProductionContext context, TranslationModelSet translations)
    {
        const string className = "LanguageStrings";
        var body = GenerateMembers(translations.Files, translations.FallbackLanguage);
        var sourceBody = $$"""
                 public static class {{className}}
                 {
                 {{body}}
                 }
                 """;
        var source = $$"""
                   #nullable enable
                   // <auto-generated/>
                   using System.Collections.Generic;
                   using System.Globalization;

                   #pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
                   {{TranslationGeneratorUtilities.WrapInNamespace(sourceBody, translations.GeneratedNamespace)}}
                   """;

        context.AddSource($"{className}.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateMembers(EquatableArray<LanguageFileModel> files, string fallbackLanguage)
    {
        var builder = new StringBuilder();
        builder.AppendLine("    private static readonly Dictionary<string, Dictionary<string, string>> languages = new()");
        builder.AppendLine("    {");

        foreach (var file in files.Array.OrderBy(static file => file.Language, StringComparer.Ordinal))
        {
            builder.AppendLine($"        [{TranslationGeneratorUtilities.ToCSharpStringLiteral(file.Language)}] = new Dictionary<string, string>");
            builder.AppendLine("        {");

            foreach (var entry in file.Entries)
            {
                builder.AppendLine($"            [{TranslationGeneratorUtilities.ToCSharpStringLiteral(entry.KeyPath)}] = {TranslationGeneratorUtilities.ToCSharpStringLiteral(entry.Value)},");
            }

            builder.AppendLine("        },");
        }

        builder.AppendLine("    };");
        builder.AppendLine();
        builder.AppendLine("    public static string GetString(string key)");
        builder.AppendLine("    {");
        builder.AppendLine("        var culture = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;");
        builder.AppendLine("        if (!languages.ContainsKey(culture))");
        builder.AppendLine($"            culture = {TranslationGeneratorUtilities.ToCSharpStringLiteral(fallbackLanguage)};");
        builder.AppendLine();
        builder.AppendLine("        return languages.TryGetValue(culture, out var dictionary) && dictionary.TryGetValue(key, out var value)");
        builder.AppendLine("            ? value");
        builder.AppendLine("            : key;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static string? GetStringOrNull(string key)");
        builder.AppendLine("    {");
        builder.AppendLine("        var culture = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;");
        builder.AppendLine("        if (!languages.ContainsKey(culture))");
        builder.AppendLine($"            culture = {TranslationGeneratorUtilities.ToCSharpStringLiteral(fallbackLanguage)};");
        builder.AppendLine();
        builder.AppendLine("        return languages.TryGetValue(culture, out var dictionary) && dictionary.TryGetValue(key, out var value)");
        builder.AppendLine("            ? value");
        builder.AppendLine("            : null;");
        builder.AppendLine("    }");

        return builder.ToString();
    }
}