using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace BccCode.I18N.SourceGen;

[Generator]
public class I18NLanguageDictGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var files = context.AdditionalTextsProvider
            .Where(x => x.Path.EndsWith(".json"))
            .Collect();

        var fallbackLanguage = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.FallbackLanguage", out var lang);
                return string.IsNullOrWhiteSpace(lang) ? "no" : lang!;
            });

        var provider = files.Combine(fallbackLanguage);

        context.RegisterSourceOutput(provider, (ctx, tuple) => GenerateCode(ctx, tuple.Left, tuple.Right));
    }

    private void GenerateCode(SourceProductionContext context, ImmutableArray<AdditionalText> files, string fallbackLanguage)
    {
        const string className = "I18NStrings";

        try
        {
            var keys = files
                .Select(GetLanguageMap)
                .ToDictionary(x=>x.language, x=> x.Item2);

            var body = GenerateCSharp(keys, fallbackLanguage);
            var source = $$"""
                           #nullable enable
                           // <auto-generated/>
                           using System.Globalization;
                           using System.Collections.Generic;
                           
                           #pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
                           public static class {{className}}
                           {
                           {{body}}
                           }
                           """;
            context.AddSource($"{className}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
        catch (Exception e)
        {
            context.AddSource($"{className}.g.cs", SourceText.From($"{e.Message}\n{e.StackTrace}", Encoding.UTF8));
        }
    }

    private static (string language, Dictionary<string, string>) GetLanguageMap(AdditionalText additionalFile)
    {
        var language = Path.GetFileNameWithoutExtension(additionalFile.Path);

        var content = additionalFile?.GetText()?.ToString();
        if (content == null)
            return (language, []);

        using var doc = JsonDocument.Parse(content);
        if (doc.RootElement.ValueKind != JsonValueKind.Object)
            return (language, []);

        return (language, GetLanguageMap(doc.RootElement)
            .ToDictionary(x=>x.Item1, x => x.Item2));
    }

    private static IEnumerable<(string, string)> GetLanguageMap(JsonElement root, string? outerPath = null)
    {
        foreach (var prop in root.EnumerateObject())
        {
            var name = prop.Name;
            var key = outerPath == null ? name : outerPath + "." + name;
            if (prop.Value.ValueKind == JsonValueKind.String)
            {
                yield return (key, prop.Value.ToString());
            }
            else if (prop.Value.ValueKind == JsonValueKind.Object)
            {
                foreach (var valueTuple in GetLanguageMap(prop.Value, key))
                {
                    yield return valueTuple;
                }
            }

        }
    }


    private static string GenerateCSharp(
        Dictionary<string, Dictionary<string, string>> languages, string fallbackLanguage)
    {
        var dictionary = new StringBuilder();
        
        dictionary.AppendLine("private static readonly Dictionary<string, Dictionary<string, string>> languages = new() {");

        foreach (var language in languages)
        {
            dictionary.AppendLine($"[\"{language.Key}\"] = new Dictionary<string, string> {{");
            foreach (var entry in language.Value)
            {
                dictionary.AppendLine($"[\"{entry.Key}\"] = \n\"\"\"\n{entry.Value}\n\"\"\",");
            }
            dictionary.AppendLine("},");
        }
        
        dictionary.AppendLine("};");
            
        
        return $$"""
               {{dictionary}}
               
               public static string GetString(string key) {
                   var culture = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
                   if(!languages.ContainsKey(culture))
                       culture = "{{fallbackLanguage}}"; // Fallback language
                   return languages.TryGetValue(culture, out var dict) && dict.TryGetValue(key, out var value)
                       ? value
                       : key;
               }
               
               public static string? GetStringOrNull(string key) {
                   var culture = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
                   if(!languages.ContainsKey(culture))
                       culture = "{{fallbackLanguage}}"; // Fallback language
                   return languages.TryGetValue(culture, out var dict) && dict.TryGetValue(key, out var value)
                       ? value
                       : null;
               }
               """;
    }

    private static string SanitizeName(string name)
    {
        // Very basic: replace invalid identifier characters with '_'
        var sb = new StringBuilder();
        if (!SyntaxFacts.IsIdentifierStartCharacter(name[0]))
            sb.Append('_');
        if (SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None)
            sb.Append("@");
        foreach (var c in name)
            sb.Append(SyntaxFacts.IsIdentifierPartCharacter(c) ? c : '_');

        return sb.ToString();
    }
}